export const endpoints = {
  eevee: {
    documentTypesList: '/api/v1/eevee/category/documents/list/',
    signupUser: '/api/v1/eevee/signup/',
    validateSignupUser: '/api/v1/eevee/signup/validate/',
    verifyHubspotSignup: '/api/v1/eevee/signup/update/',
    loginAppUser: '/api/v1/eevee/login/',
    logoutUser: '/api/v1/eevee/logout/',
    getUser: '/api/v1/eevee/user/',
    addMember: '/api/v1/eevee/signup/users/',
    getMembers: '/api/v1/eevee/users/member/list/',
    editMember: '/api/v1/eevee/users/member/edit/',
    deleteMember: '/api/v1/eevee/delete/users/',
    sendFeedback: '/api/v1/eevee/users/feedback/',
    getConfig: '/api/v1/eevee/config/',
    getDocTypeConfig: '/api/v1/eevee/config/doc_types/',
    updateConfigFlags: '/api/v1/eevee/config/flag/',
    updateUserSettings: '/api/v1/eevee/users/settings/',
    forgetUserPassword: '/api/v1/eevee/forget_password/new_token/',
    validateToken: '/api/v1/eevee/validate/fp_token/',
    resetUserPassword: '/api/v1/eevee/forget_password/change_password/',
    changeUserPassword: '/api/v1/eevee/users/settings/password/',
    updateDocumentDeleteAfter: '/api/v1/eevee/config/del_doc_after/',
    setTempTokenDuration: '/api/v1/eevee/config/temp_token_duration/',
    updateStraightThroughProcessingFlags: '/api/v1/eevee/config/flag/',
    updateUserSettingsWebhookUrl: '/api/v1/eevee/config/webhook/',
    refreshUserDocsumoApiKey: '/api/v1/eevee/apikey/refresh/',
    getDocumentCounts: '/api/v1/eevee/documents/count/',
    getDocuments: '/api/v1/eevee/documents/',
    downloadProcessedDocuments: '/api/v1/eevee/documents/download/',
    downloadDocumentByFormat: '/api/v1/eevee/documents/download/single/',
    uploadDocument: '/api/v1/eevee/documents/upload/',
    deleteDocument: '/api/v1/eevee/documents/{docId}/',
    viewUserDocsumoApiKey: '/api/v1/eevee/config/apikey/',
    getWebhookData: '/api/v1/eevee/config/get/webhook/',
    previewOriginalDocument: '/api/v1/eevee/preview/document/{docId}/',
    validateLogin: '/api/v1/eevee/validate/login/',
    linkAccountWithSocial: '/api/v1/eevee/link/social/',
    setupMFAFlow: '/api/v1/eevee/setup/mfa/',
    enableMFA: '/api/v1/eevee/enable/mfa/',
    disableMFA: '/api/v1/eevee/disable/mfa/',
    fetchSsoSettings: '/api/v1/eevee/fetch/sso/details/',
    requestSsoSetup: '/api/v1/eevee/request/sso/',
    testSsoSetup: '/api/v1/eevee/test/sso/',
    validateSsoIdToken: '/api/v1/eevee/test/sso/status/',
    enableOrDisableSso: '/api/v1/eevee/update/sso/',
    deleteSsoSetup: '/api/v1/eevee/update/sso/',
    getSsoProvider: '/api/v1/eevee/validate/sso/status/',
    enableSingleMFA: '/api/v1/eevee/enable/mfa/single/',
    resetMFARecovery: '/api/v1/eevee/reset/mfa/recovery/',
    resetMFARecoveryFromAuth: '/api/v1/eevee/reset/mfa/recovery/single/',
    resetRequest: '/api/v1/eevee/reset/mfa/request/',
    resetRequestFromAuth: '/api/v1/eevee/reset/mfa/request/single/',
    resetMfaOfUser: '/api/v1/eevee/reset/mfa/',
    switchAccountMode: '/api/v1/eevee/mode/',
    sendTokenOnReviewUrl: '/api/v1/eevee/config/review_url_token/',
    switchUser: '/api/v1/eevee/ui/mode/',
    moveFiles: 'api/v1/eevee/documents/move/',
    pubnubLogs: '/api/v1/eevee/logs/pubsub/',
    requestDocTypeAccess: '/api/v1/eevee/users/member/access/',
    hubspotIdentificationToken: '/api/v1/eevee/user/hubspot-visitor-token/',
  },
  pik: {
    splitDocument: '/api/v1/pik/documents/split/',
    splitClassifyDocument: '/api/v1/pik/documents/split_v2/',
    startReview: '/api/v1/pik/review/start/',
    startDocumentReview: '/api/v1/pik/review/{docId}/start/',
    finishDocumentReview: '/api/v1/pik/review/{docId}/end/',
    skipDocumentReview: '/api/v1/pik/review/{docId}/skip/',
    getDocumentBboxes: '/api/v1/pik/documents/{docId}/bboxes/',
    realTimeUpdateField:
      '/api/v1/pik/documents/{docId}/update/field/multiple/{itemId}/',
    getDocumentSearchBboxes:
      '/api/v1/pik/documents/{docId}/search/text/review/',

    getTextFromBbox: '/api/v1/pik/documents/{docId}/search/text/',
    updateFieldData: '/api/v1/pik/documents/{docId}/update/field/{fieldId}/',
    reviewAddSimilarLines:
      '/api/v1/pik/documents/{docId}/line-items/{sectionFieldId}/add-similar-lines/',
    addTableMultiplePage:
      '/api/v1/pik/documents/{docId}/line-items/{parentId}/add-similar-lines/',
    updateOnClose: '/api/v1/pik/review/{docId}/close/',
    saveSpreadsheetFile: '/api/v1/pik/review/excel/{docId}/close/',
    startSpreadsheetReview: '/api/v1/pik/review/excel/{docId}/start/',
    finishSpreadsheetReview: '/api/v1/pik/review/excel/{docId}/end/',
    getSummaryPanelData: '/api/v1/pik/documents/{docId}/static/data/',
    saveSpreadsheetSummaryData:
      '/api/v1/pik/documents/{docId}/static/data/add/',

    // CHATAI
    enableChatAI: '/api/v1/pik/chatai/enable/',
    requestChatAI: '/api/v1/pik/chatai/request/',
    askQuestion: '/api/v1/pik/chatai/{docId}/',
    chatAIHistory: '/api/v1/pik/chatai/history/{docId}/',
    retryQuestion: '/api/v1/pik/chatai/retry/{docId}/{chatId}/',
    likeUnlikeMessage: '/api/v1/pik/chatai/flag/{docId}/{chatId}/',

    //Table grid version 1
    deleteDocumentGrids: '/api/v1/pik/tablegrid/{docId}/{parentId}/',
    pasteGrid: '/api/v1/pik/tablegrid/copy/paste/{docId}/{parentId}/',
    tagDocumentGrids: '/api/v1/pik/tablegrid/add/{docId}/{parentId}/',

    getDocumentDataV1: '/api/v1/pik/documents/{docId}/data/',
    getDocumentAllTableGridsV1: '/api/v1/pik/tablegrid/{docId}/',
    getDocumentGridsV1: '/api/v1/pik/tablegrid/{docId}/{parentId}/',
    postDocumentGridsV1: '/api/v1/pik/tablegrid/{docId}/{parentId}/',
    extractGridDataV1:
      '/api/v1/pik/tablegrid/extract/{docId}/{sectionFieldId}/',
    addDocumentGridsV1: '/api/v1/pik/tablegrid/add/new/{docId}/{parentId}/',
    reviewAddLineV1:
      '/api/v1/pik/documents/{docId}/line-items/{sectionFieldId}/add-line/',
    reviewDeleteLineItemFieldsV1:
      '/api/v1/pik/documents/{docId}/line-items/{sectionFieldId}/',

    // Table grid Version 2 API
    getDocumentData: '/api/v2/pik/documents/{docId}/data/',
    getDocumentAllTableGrids: '/api/v2/pik/tablegrid/{docId}/',
    getAllLineitemsGrids: '/api/v2/pik/tablegrid/fetch/{docId}/',
    getDocumentGrids: '/api/v2/pik/tablegrid/{docId}/{parentId}/',
    postDocumentGrids: '/api/v2/pik/tablegrid/{docId}/{parentId}/',
    extractGridData: '/api/v2/pik/tablegrid/extract/{docId}/{sectionFieldId}/',
    addDocumentGrids: '/api/v2/pik/tablegrid/add/new/{docId}/{parentId}/',
    extractSimilarTables:
      '/api/v2/pik/tablegrid/extract-similar-tables/{docId}/{parentId}/',
    reviewAddLine:
      '/api/v2/pik/documents/{docId}/line-items/{sectionFieldId}/add-line/',
    reviewDeleteLineItemFields:
      '/api/v2/pik/documents/{docId}/line-items/{sectionFieldId}/',
  },
  mew: {
    getUserFlow: '/api/v1/mew/users/tooltip/',
    getAllDocumentsTypes: '/api/v1/mew/documents/types/',
    createDocumentType: '/api/v1/mew/documents/types/new/',
    createNewFolder: '/api/v1/mew/folder/add/',
    editNewFolder: '/api/v1/mew/folder/edit/',
    getFolderDetail: '/api/v1/mew/folders/detail/{folderId}/',
    duplicateDocumentType: '/api/v1/mew/documents/types/duplicate/',
    updateDocumentTypeTitle: '/api/v1/mew/documents/types/{docId}/',
    retryDocuments: '/api/v1/mew/documents/retry/',
    changeDocType: '/api/v1/mew/documents/change_type/',
    changeUserType: '/api/v1/mew/documents/change_user/',
    deleteDocAndFolder: '/api/v1/mew/folder/delete/',
    pullDocFromProd: '/api/v1/mew/documents/types/pull/',
    pushDocFromProd: '/api/v1/mew/documents/types/push/',
    downlaodMultiDocs: '/api/v1/mew/documents/download/',
    replaceModel: '/api/v1/mew/ml/update/{modelId}/?override={override}/',
    downloadAllDocs: '/api/v1/mew/documents/download_all/',

    deleteDocumentType: '/api/v1/mew/documents/types/{docId}/',
    resetDocumentType: '/api/v1/mew/documents/reset/{docType}/',
    editFieldReview: '/api/v1/mew/fields/edit/start/{docType}/',
    updateFieldAndSection:
      '/api/v1/mew/filters/move/item/{docType}/{docId}/{itemId}/',
    saveAndCloseData: '/api/v1/mew/fields/save/',
    getDocumentDDValues: '/api/v1/mew/drop_down/detail/{itemId}/',
    getDocumentDDOptions: '/api/v1/mew/drop_down/detail/{id}/',
    getEditFieldDocumentBboxes:
      '/api/v1/mew/filters/edit/bbox/{docType}/{docId}/',
    getEditFieldDocumentData: '/api/v1/mew/fields/{docType}/{docId}/data/',
    editFieldAddFooterColumn: '/api/v1/mew/fields/add/{docType}/{parentId}/',
    addNewSectionTable: '/api/v1/mew/section/add/{docType}/{sectionType}/',
    updateSectionTitle: '/api/v1/mew/section/edit/{docType}/{id}/',
    deleteSection: '/api/v1/mew/section/delete/{docType}/{id}/',
    addSectionField: '/api/v1/mew/fields/add/{docType}/{parentId}/',
    updateSectionField: '/api/v1/mew/fields/edit/{docType}/{fieldId}/',
    deleteSectionField: '/api/v1/mew/fields/delete/{docType}/{fieldId}/',
    filterSectionField: '/api/v1/mew/fields/settings/{docType}/{fieldId}/',
    getFilterList: '/api/v1/mew/fields/settings/options/',
    additionalFilter:
      '/api/v1/mew/filter/change/data_type/{docType}/{docId}/{fieldId}/',
    changeFilter: '/api/v1/mew/fields/settings/{docType}/{fieldId}/update/',
    saveAndCloseFilter: '/api/v1/mew/filter/save/{docType}/{id}/',
    getServices: '/api/v1/mew/documents/types/api/list/',
    updateStatusServices: '/api/v1/mew/documents/types/api/update/{service}/',
    uploadDummyDocOfServices:
      '/api/v1/mew/documents/types/api/upload/{service}/',
    getFilterDataType: '/api/v1/mew/fields/data-types/',
    getCustomFilterData: '/api/v1/mew/dt/setting/fetch/{docType}/',
    updateCustomFilterData: '/api/v1/mew/dt/setting/update/{docType}/',
    getValidation: '/api/v1/mew/validate/key/{docType}/{docId}/{parentId}/',
    customValidation: '/api/v1/mew/validate/dt/custom_processing/{docType}/',
    getGeneralAnalytics: '/api/v1/mew/analytics/general/{docType}/',
    getAccuracyAnalytics: '/api/v1/mew/analytics/accuracy/{docType}/',
    nlpTraining: '/api/v1/mew/ml/nlp/train/',
    downloadTextDocument: '/api/v1/mew/documents/download/text/{docId}/',
    getTrainVersion: '/api/v1/mew/ml/nlp/list/{docType}/',
    getCurrentVersion: '/api/v1/mew/ml/dc/get/version/',
    getSelectedDocumentTypes: '/api/v1/mew/ml/dc/get/docs/',
    getTrainableStatus: '/api/v1/mew/ml/dc/get/status/',
    startAutoClassify: '/api/v1/mew/ml/dc/train/',
    updateClassificationVersion: '/api/v1/mew/ml/dc/update/{version}/',
    getAutoClassifyVersion: '/api/v1/mew/ml/dc/list/',
    getMODELList: '/api/v1/mew/ml/generic/models/',
    trainCurrentModel: '/api/v1/mew/ml/generic/train/',
    getModelSingleViewData: '/api/v1/mew/ml/generic/models/{mId}/',
    deleteModel: '/api/v1/mew/ml/generic/models/',
    getComparision: '/api/v1/mew/ml/generic/models/compare/',
    getDownloadReport: '/api/v1/mew/analytics/report/{docType}/',
    downloadSpreadsheetFile: '/api/v1/mew/documents/download/excel/{docId}/',
    getModelTypes: '/api/v1/mew/ml/generic/models/list/',
    editFileOrFolderName: '/api/v1/mew/documents/rename/',
    getDocumentModelConfig: '/api/v1/mew/ml/generic/models/config/',
    downloadFolderDocs: '/api/v1/mew/folders/download/',
    renameModel: '/api/v1/mew/ml/generic/models/',
    validateDocumentTitle: '/api/v1/mew/validate/dt/title/',
    getDocumentTypeAccess: '/api/v1/mew/documents/types/api/status/{docType}/',
    changeFieldType: '/api/v1/mew/fields/{docType}/{fieldId}/type/',
    changeFieldOrder: '/api/v1/mew/fields/{docType}/action/change-order/',
    cancelSavedChanges: '/api/v1/mew/fields/cancel/',
    changeFieldVisibility: '/api/v1/mew/fields/{docType}/{fieldId}/visibility/',
    triggerCreditNotification: '/api/v1/mew/credit/notify/',
  },
  raichu: {
    updateCSVTitle: '/api/v1/raichu/drop_down/db/rename/{docId}/',
    deleteCsv: '/api/v1/raichu/drop_down/db/delete/',
    deleteCsvRow: '/api/v1/raichu/drop_down/db/update/{ddId}/',
    addCsvRowLine: '/api/v1/raichu/drop_down/db/addrow/{ddId}/',
    downloadCsv: '/api/v1/raichu/drop_down/db/download/',
    uploadCsvDocument: '/api/v1/raichu/drop_down/db/add/',
    updateCsvDocument: '/api/v1/raichu/drop_down/db/update/{ddId}/',
    updateCsvField: '/api/v1/raichu/drop_down/db/update/single/{ddId}/',
    getTableViewData: '/api/v1/raichu/drop_down/db/get/{ddId}/',
    getDocumentDDMValues:
      '/api/v1/raichu/drop_down/db/detail/{docType}/{docId}/{itemId}/',
    getDocumentSettingFilterList: '/api/v1/raichu/dt/setting/fetch/list/',
    getDocTypeSetting: '/api/v1/raichu/dt/setting/fetch/{docType}/',
    getDocTypeViewChanges: '/api/v1/raichu/dt/setting/view/changes/{docType}/',
    changeDocTypeSetting: '/api/v1/raichu/dt/setting/update/{docType}/',
    getTempToken: '/api/v1/raichu/temp_token/create/{docId}/',
    getLogInfo: '/api/v1/raichu/log/get/',
    getActivity: '/api/v1/raichu/log/get/',
    getActivityCounts: '/api/v1/raichu/log/count/',
    getCSVHeader: '/api/v1/raichu/drop_down/headers/{dropDownId}/',
    getCSVList: '/api/v1/raichu/drop_down/db/list/',
    getModelDDList: 'api/v1/raichu/dt/setting/ml/{id}/',
    getNotificationPreference: '/api/v1/raichu/notification/get/',
    updateNotificationPreference: '/api/v1/raichu/notification/update/',
    getLookupData: '/api/v1/raichu/drop_down/db/get/lookup/coa_classification/',
    resetCustomCode: '/api/v1/raichu/dt/setting/reset/{docType}/',
    getFilterDataList: '/api/v1/raichu/log/filters/',
    postTrackingData: '/api/v1/raichu/track/review-screen/',
  },
};
