export const ERROR_TYPES = {
  BAD_REQUEST: 'BAD_REQUEST',
  DUPLICATE_EMAIL: 'DUPLICATE_EMAIL',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  REQUEST_ERROR: 'REQUEST_ERROR',
};
